# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller build for Supercut Extended.

ffmpeg/ffprobe ARE bundled, from vendor/ffmpeg/ -- run `python tools/fetch_ffmpeg.py`
first, the binaries are not in git. They ride along as *datas* rather than binaries so
PyInstaller copies them verbatim instead of scanning them for DLL dependencies they do
not need rewritten. The GPLv3 licence and NOTICE travel with them, which is what makes
redistributing the build legal.

PySide6 ships a lot of modules this app never touches (WebEngine alone is hundreds of
megabytes). Excluding them is what keeps the build a sane size.

ONEFILE controls the output shape:

    True   one self-contained .exe per entry point. Nothing else needs to travel with
           it, at the cost of unpacking the whole payload into %TEMP% on every launch.
    False  a folder holding small .exe stubs plus a shared _internal/. Starts faster
           and the two executables share one copy of the payload, but the folder has
           to be kept together.
"""

ONEFILE = False

import os

from PyInstaller.utils.hooks import collect_data_files  # noqa: F401  (kept for reference)

ICON_DIR = "cooliocns SVG"

# Multi-resolution .ico, generated by `python tools/make_icon.py`. It is both compiled
# into the executables and shipped as data, so the taskbar/window icon at runtime is
# the same image Explorer shows on the file.
APP_ICON = "assets/app.ico"

# Bundled ffmpeg. Landed at the root of the bundle so probe._search_roots() finds it
# first, both next to a onedir exe and inside a one-file build's _MEIPASS.
FFMPEG_DIR = "vendor/ffmpeg"
FFMPEG_FILES = ("ffmpeg.exe", "ffprobe.exe",
                "LICENSE-FFmpeg-GPLv3.txt", "NOTICE.txt")

_missing = [f for f in FFMPEG_FILES
            if not os.path.isfile(os.path.join(FFMPEG_DIR, f))]
if _missing:
    raise SystemExit(
        f"missing from {FFMPEG_DIR}: {', '.join(_missing)}\n"
        "Run `python tools/fetch_ffmpeg.py` first (the binaries are not in git)."
    )

FFMPEG_DATAS = [(os.path.join(FFMPEG_DIR, f), ".") for f in FFMPEG_FILES]

QT_EXCLUDES = [
    "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets", "PySide6.QtWebEngineQuick",
    "PySide6.QtWebChannel", "PySide6.QtWebSockets", "PySide6.QtQuick", "PySide6.QtQuick3D",
    "PySide6.QtQml", "PySide6.QtQuickWidgets", "PySide6.Qt3DCore", "PySide6.Qt3DRender",
    "PySide6.Qt3DAnimation", "PySide6.Qt3DExtras", "PySide6.Qt3DInput", "PySide6.Qt3DLogic",
    "PySide6.QtCharts", "PySide6.QtDataVisualization", "PySide6.QtGraphs",
    # NOTE: QtMultimedia / QtMultimediaWidgets are REQUIRED -- the preview player uses
    # QMediaPlayer + QVideoWidget. QtSvg is REQUIRED -- the icon set is SVG.
    # Do not add either back to this list.
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets", "PySide6.QtBluetooth", "PySide6.QtNfc", "PySide6.QtPositioning",
    "PySide6.QtLocation", "PySide6.QtSerialPort", "PySide6.QtSerialBus", "PySide6.QtTest",
    "PySide6.QtSql", "PySide6.QtDesigner", "PySide6.QtHelp", "PySide6.QtUiTools",
    "PySide6.QtOpenGL", "PySide6.QtOpenGLWidgets", "PySide6.QtSpatialAudio",
    "PySide6.QtRemoteObjects", "PySide6.QtScxml", "PySide6.QtSensors", "PySide6.QtStateMachine",
    "PySide6.QtTextToSpeech", "PySide6.QtHttpServer", "PySide6.QtNetworkAuth",
]

OTHER_EXCLUDES = [
    "tkinter", "unittest", "pydoc_data", "lib2to3", "test",
    "numpy", "pandas", "matplotlib", "PIL", "scipy",
]

# Excluding a PySide6 module stops its Python bindings being imported, but the Qt DLLs
# still get swept up by the binary collection. Drop them by name as well.
DROP_BINARIES = (
    "qt6quick", "qt6qml", "qt6qmlmodels", "qt6qmlmeta", "qt6qmlworkerscript",
    "qt6quickcontrols2", "qt6quicktemplates2", "qt6quickparticles", "qt6quickshapes",
    "qt6quickeffects", "qt6quicklayouts", "qt6quickdialogs2", "qt6quicktest",
    # Software OpenGL rasteriser (~20 MB). This is a QWidget app that never asks for
    # an OpenGL surface, so Qt's raster backend covers it.
    "opengl32sw",
    "qt6pdf", "qt6designer", "qt63d", "qt6charts", "qt6datavisualization",
    "qt6sensors", "qt6test", "qt6sql", "qt6bluetooth",
    # qt6multimedia* and qt6svg* stay: the player and the icon set need them.
)


def keep_binary(entry):
    name = entry[0].lower().rsplit("/", 1)[-1].rsplit("\\", 1)[-1]
    stem = name.split(".")[0]
    return stem not in DROP_BINARIES


a = Analysis(
    ["supercut.py"],
    pathex=[],
    binaries=[],
    # Ship the coolicons set alongside the app; icons.icon_root() finds it via _MEIPASS.
    datas=[(ICON_DIR, ICON_DIR), ("assets", "assets")] + FFMPEG_DATAS,
    # ccl_chromium_reader resolves several submodules lazily, so pull the package in
    # wholesale rather than trying to enumerate them.
    hiddenimports=[
        "ccl_chromium_reader",
        "ccl_chromium_reader.ccl_chromium_indexeddb",
        "ccl_chromium_reader.serialization_formats",
        "ccl_chromium_reader.serialization_formats.ccl_v8_value_deserializer",
        "ccl_chromium_reader.serialization_formats.ccl_blink_value_deserializer",
        "ccl_chromium_reader.storage_formats",
        "ccl_chromium_reader.storage_formats.ccl_leveldb",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=QT_EXCLUDES + OTHER_EXCLUDES,
    noarchive=False,
    optimize=0,
)

a.binaries = TOC(entry for entry in a.binaries if keep_binary(entry))

pyz = PYZ(a.pure)

COMMON = dict(
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=APP_ICON,
)


def build_exe(name, console):
    """One executable, in whichever shape ONEFILE asks for.

    In one-file mode the payload is appended to each executable, so the two entry
    points cannot share it the way they do under COLLECT.
    """
    if ONEFILE:
        return EXE(pyz, a.scripts, a.binaries, a.datas, [],
                   name=name, console=console, runtime_tmpdir=None, **COMMON)
    return EXE(pyz, a.scripts, [], exclude_binaries=True,
               name=name, console=console, **COMMON)


# console=False so launching the GUI never flashes a terminal; the CLI is built on the
# console subsystem so `SupercutExtended-cli.exe list` has somewhere to print.
exe = build_exe("SupercutExtended", console=False)
exe_cli = build_exe("SupercutExtended-cli", console=True)

if not ONEFILE:
    coll = COLLECT(
        exe,
        exe_cli,
        a.binaries,
        a.datas,
        strip=False,
        upx=False,
        upx_exclude=[],
        name="SupercutExtended",
    )
